name: Validate JSONC Files

on:
  pull_request:

jobs:
    steps:
      - uses: PopTracker/pack-checker-action@v1
        with:
          strict: true
          schema: path/to/schema
          pack: path/to/pack
          check-legacy-compat: true